"""Core data models using dataclasses with slots for memory efficiency."""

from dataclasses import dataclass, field
from typing import Optional, Dict, Any
from datetime import datetime


@dataclass(frozen=True, slots=True)
class Signal:
    """Trading signal generated by an agent.
    
    Using frozen dataclass ensures immutability and slots reduces memory by ~76%.
    """
    direction: str  # 'bullish', 'bearish', 'neutral'
    confidence: float  # 0.0 to 1.0
    reasoning: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate signal data."""
        if self.direction not in ('bullish', 'bearish', 'neutral'):
            raise ValueError(f"Invalid direction: {self.direction}")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be 0-1, got {self.confidence}")


@dataclass(frozen=True, slots=True)
class LLMConfig:
    """Configuration for LLM providers.
    
    Supports system prompts for agent personas.
    """
    provider: str  # 'openai', 'anthropic', 'ollama'
    model: str
    api_key: Optional[str] = None
    base_url: Optional[str] = None  # For Ollama
    temperature: float = 0.7
    max_tokens: int = 1000
    system_prompt: Optional[str] = None  # Agent persona
    
    def __post_init__(self):
        """Validate configuration."""
        if self.provider not in ('openai', 'anthropic', 'ollama'):
            raise ValueError(f"Unsupported provider: {self.provider}")


@dataclass(frozen=True, slots=True)
class RAGConfig:
    """Configuration for RAG system."""
    chunk_size: int = 500
    chunk_overlap: int = 50
    top_k: int = 3
    embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2"


@dataclass(frozen=True, slots=True)
class AgentConfig:
    """Complete agent configuration."""
    name: str
    description: str
    llm: Optional[LLMConfig] = None
    rag: Optional[RAGConfig] = None
    parameters: Dict[str, Any] = field(default_factory=dict)